### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by HC-teemo** [felicedeluca/graphmetrics#1]
Hello, thank you for making such a useful program. But when the program runs to step `stress` on my computer, the following error occurs.
```
Graph with 4475 nodes and 4652 edges

CR: 66886
AR: 0.22085028501514764
758.3967842699609
UE: 0.601
Traceback (most recent call last):
  File "metricscomputer.py", line 110, in <module>
    stress_val = stress.stress(G, weighted=False)
  File "/mnt/f/graphmetrics-master/stress.py", line 126, in stress
    alpha = computeScalingFactor(S_original, all_sp)
  File "/mnt/f/graphmetrics-master/stress.py", line 44, in computeScalingFactor
    source = S.node[sourceStr]
AttributeError: 'Graph' object has no attribute 'node'
```
I don't know the cause of the problem because I don't know python. I'm sorry to bother you, but can you help me? 
My OS is Ubuntu 20.04.

**Comment by felicedeluca** [comment]
A package may be missing

**Comment by HC-teemo** [comment]
Thank you for your reply. I have solved the problem. Just change `node` to `nodes`. The error may be caused by networkx changing the method name.

**Comment by felicedeluca** [comment]
> Thank you for your reply. I have solved the problem. Just change `node` to `nodes`. The error may be caused by networkx changing the method name.

Thank you. If you want, please send a pull request with fix and I’ll update the project
